;;; flymake-shellcheck-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-shellcheck.el

(autoload 'flymake-shellcheck-load "flymake-shellcheck" "\
Add the Shellcheck backend into Flymake's diagnostic functions list.")
(register-definition-prefixes "flymake-shellcheck" '("flymake-shellcheck-"))

;;; End of scraped data

(provide 'flymake-shellcheck-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-shellcheck-autoloads.el ends here
