#!/bin/env zsh
DefaultSaveDir="$HOME/capture"

coordinate=$(slurp) || exit
grim -l 0 -g "$coordinate" || exit

SavePath=$( zenity \
    --file-selection \
    --save \
    --confirm-overwrite \
    --file-filter=*.png \
    --filename="$DefaultSaveDir/.png" \
) || exit

case "$SavePath" in
    *.png) ;;
    *) SavePath="$SavePath.png" ;;
esac
# [[ $SavePath =~ \.png$ ]] || SavePath+='.png'
