#!/usr/bin/env dash
DefaultSaveDir="~/capture/.png"

coordinate=$(slurp) || exit
grim -l 0 -g "$coordinate" || exit

SavePath=$( zenity \
    --file-selection \
    --save \
    --confirm-overwrite \
    # --file-filter=*.png \
    --filename="$DefaultSaveDir" \
) || exit

case "$SavePath" in
    *.png) ;;
    *) SavePath="$SavePath.png" ;;
esac
# [[ $SavePath =~ \.png$ ]] || SavePath+='.png'
