#! /usr/bin/env zsh
#export app=emacs
#export app=$(echo -e 'emacs\nfirefox\nqutebrowser\nqemu' | fzf --prompt 'cmd/' )

#case $app in
#	qemu) 
#		virt-manager > /dev/null 2>&1 & disown
#		;;
#	foot)
#		foot --log-level none --log-no-syslog > /dev/null 2>&1 & disown
#		;;
#	*)
#		$app > /dev/null 2>&1 & disown
#		;;
#esac
	
foot > /dev/null 2>&1 & disown
