#!/usr/bin/env zsh
waylock -log-level error -fork-on-lock -ignore-empty-password -init-color 0x6277a4 -input-color 0x587539 -fail-color 0xf52a65 #&&  ##0xffb86c 
# waylock -log-level error -ignore-empty-password -init-color 0x6277a4 -input-color 0x587539 -fail-color 0xf52a65 #&&  ##0xffb86c 
sleep 3
doas /usr/bin/systemctl -f -q suspend-then-hibernate
