#!/usr/bin/env zsh
pacman_log=$(doas pacman -Syyu --noconfirm)

# 提取升级包的信息
export package_list=$(printf "$pacman_log" | awk '/^Packages/ {
	for(i=3; i<=NF; i+=3) {
		print $i
	}
}')

footclient -T alert -W 40x15 zsh -c $'
text="Upgration completed. Here\'s the list:"
printf "$text\n$package_list"
case "$package_list" in
	'linux-clear-x64-v3')
		read -s -p "You actually need a reboot"
		;;
	*)
		read -s
		;;
esac
'
