#!/usr/bin/env zsh
tmp_file=/tmp/key-value

footclient --log-level none -T spotlight -W 15x15 zsh -c \
    "pmenu -p 'open ' blender chromium emacs epiphany firefox foot inkscape rosenrot qemu qutebrowser virtualbox windows> '$tmp_file'"

app=$(cat "$tmp_file") || exit

case "$app" in
    # "")
    #     exit 0
    #     ;;
    emacs)
        nohup /usr/bin/emacsclient -a '' -c > /dev/null 2>&1 &
        ;;
    epiphany)
        nohup /usr/bin/epiphany > /dev/null 2>&1 &
        ;;
    foot)
        nohup /usr/bin/footclient --log-level none > /dev/null 2>&1 &
        ;;
    matlab)
        nohup QT_QPA_PLATFORM=xcb /usr/local/bin/matlab > /dev/null 2>&1 &
        ;;
    qemu) 
        nohup /usr/bin/virt-manager > /dev/null 2>&1 &
        ;;
    windows)
        nohup virt-viewer -a win11 > /dev/null 2>&1 &
        virsh start win11 > /dev/null
        ;;
    *)
        if which "$app" > /dev/null 2>&1 ; then
            nohup /usr/bin/$app > /dev/null 2>&1 &
        # else
            # firefox --new-tab --search "$app"
            # /usr/bin/qutebrowser --target auto "$app" > /dev/null 2>&1 &
        fi
        ;;
esac
