#!/usr/bin/bash
set -eu -o pipefail

app=$(pmenu -p 'open ' audacity blender chromium emacs epiphany firefox foot gimp inkscape matlab rosenrot pcmanfm qemu qutebrowser virtualbox)
# app=$(echo "audacity\nblender\nchromium\nemacs\nepiphany\nfirefox\nfoot\ngimp\ninkscape\nmatlab\nrosenrot\npcmanfm\nqemu\nqutebrowser\nvirtualbox\nwindows" | fzy -p 'open ' )

case "$app" in
    # "")
    #     exit 0
    #     ;;
    emacs)
        exec setsid /usr/bin/emacsclient -a '' -c > /dev/null 2>&1
        ;;
    foot)
        exec setsid /usr/bin/footclient --log-level none > /dev/null 2>&1
        ;;
    matlab)
        exec setsid QT_QPA_PLATFORM=xcb /usr/local/bin/matlab > /dev/null 2>&1
        ;;
    qemu) 
        exec setsid /usr/bin/virt-manager > /dev/null 2>&1
        ;;
    windows)
        exec setsid virt-viewer -a win11 > /dev/null 2>&1
        virsh start win11 > /dev/null 2>&1
        ;;
    *)
        if which "$app" > /dev/null; then
            exec setsid /usr/bin/$app > /dev/null 2>&1
        # else
            # firefox --new-tab --search "$app"
            # /usr/bin/qutebrowser --target auto "$app" > /dev/null 2>&1 &
        fi
        ;;
esac
