#!/usr/bin/bash

. /home/chaos/garden/scripts/sun

footclient --override=main.include=/home/chaos/.config/foot/dark.ini -T alert -W 20x3 bash -c '
text="Being late"
text_length=${#text}
x=$(( (20 - text_length) / 2 ))
y=$(( 3 / 2 ))
tput cup $y $x
echo "$text"
read -t 9 -k 1 -s'

footclient --override=main.include=/home/chaos/.config/foot/dark.ini -T alert -W 50x5 bash -c '
text="All work saved [Y/n]?"
text_length=${#text}
x=$(( (50 - text_length) / 2 ))
y=$(( 5 / 2 ))
tput cup $y $x
echo "$text"
read -t 600 -k 1 > /tmp/key-value.tmp'

sleep 8

confirm=$(cat /tmp/key-value.tmp)

case "$confirm" in
	''|Y\y)
		pkill emacs

		if [ "$theme" = "light" ]; then
			dark
			pkill swaybg
			nohup /usr/bin/swaybg -m fill -i "$(find /home/chaos/garden/wallpaper/dark/ -type f | sort -R | head -n 1)" > /dev/null 2>&1 &
		else
			light
			pkill swaybg
			nohup /usr/bin/swaybg -m fill -i "$(find /home/chaos/garden/wallpaper/light/ -type f | sort -R | head -n 1)" > /dev/null 2>&1 &
		fi

		# fish -c fishsun
		pkill foot
		nohup foot --server --log-no-syslog > /dev/null 2>&1 &
		;;
	*)
		:	
		;;
esac
pkill cron
