#!/usr/bin/dash

theme='light'
light() {
	sed -i '3s/dark/light/' ~/garden/scripts/sun ~/garden/scripts/wmwith ~/Parasite/etc/xdg/foot/foot.ini 
	# sed -i '22s/default-dark/rose-pine/' ~/.config/fcitx5/conf/classicui.conf
	sed -i '2s/true/false/' ~/.config/gtk-3.0/settings.ini ~/.config/gtk-4.0/settings.ini
	# sed -i '2s/true/false/' ~/.config/gtk-4.0/settings.ini
	# sed -i '3s/dark/light/' ~/Parasite/etc/xdg/foot/foot.ini
	sed -i '20s/dracula/onehalflight/' ~/Parasite/etc/xdg/nvim/sysinit.vim
	sed -i '5,7s/dracula/catppuccin/;8s/dark/light/' ~/.config/qutebrowser/config.py
	#sed -i '14,45s/^#//;49,87s/^/#/' ~/.config/zathura/zathurarc
	sed -i '2s/dracula/adwaita/' ~/.config/emacs/init.el
	# sed -i '20s/GTK_THEME=Adwaita:dark //' ~/garden/scripts/spotlight
    ln -fs ~/Parasite/.config/fzf_light ~/.config/.fzfrc
    nohup setsid /usr/bin/swaybg -m fill -i "$(find /home/chaos/garden/wallpaper/light/ -type f | sort -R | head -n 1)" > /dev/null 2>&1 &
}

dark() {
	sed -i '3s/light/dark/' ~/garden/scripts/sun ~/garden/scripts/wmwith ~/Parasite/etc/xdg/foot/foot.ini
	# sed -i '22s/rose-pine/default-dark/' ~/.config/fcitx5/conf/classicui.conf
	sed -i '2s/false/true/' ~/.config/gtk-3.0/settings.ini ~/.config/gtk-4.0/settings.ini
	# sed -i '2s/false/true/' ~/.config/gtk-4.0/settings.ini
	# sed -i '3s/light/dark/' ~/Parasite/etc/xdg/foot/foot.ini
	sed -i '20s/onehalflight/dracula/' ~/Parasite/etc/xdg/nvim/sysinit.vim
	sed -i '5,7s/catppuccin/dracula/;8s/light/dark/' ~/.config/qutebrowser/config.py
	#sed -i '14,45s/^/#/;49,87s/^#//' ~/.config/zathura/zathurarc
	sed -i '2s/adwaita/dracula/' ~/.config/emacs/init.el
	# sed -i '20s/^\([[:space:]]*\)/\1GTK_THEME=Adwaita:dark /' ~/garden/scripts/spotlight
    ln -fs ~/Parasite/.config/fzf_dark ~/.config/.fzfrc
    nohup setsid /usr/bin/swaybg -m fill -i "$(find /home/chaos/garden/wallpaper/dark/ -type f | sort -R | head -n 1)" > /dev/null 2>&1 &
}

# . /home/chaos/garden/scripts/sun

nohup /usr/bin/foot --server --log-no-syslog > /dev/null 2>&1 &

hour=$(date +%H)
if [ "$hour" -gt 16 ]  || [ "$hour" -lt 05 ]; then
    # Switch to dark mode
	dark
    # nohup setsid /usr/bin/swaybg -m fill -i "$(find /home/chaos/garden/wallpaper/dark/ -type f | sort -R | head -n 1)" > /dev/null 2>&1 &
else
    # Switch to light mode
	light
    # nohup setsid /usr/bin/swaybg -m fill -i "$(find /home/chaos/garden/wallpaper/light/ -type f | sort -R | head -n 1)" > /dev/null 2>&1 &
    # flock -n /tmp/wmscron_lock /usr/local/bin/crond -f /home/chaos/garden/scron/wmfollow_cron
fi

# gammastep -l 39:116 -b 1.0:0.9 &

# nohup /usr/bin/fcitx5 > /dev/null 2>&1 &

# dbus-update-activation-environment DISPLAY XAUTHORITY WAYLAND_DISPLAY
