import = ["/home/trunk/.config/alacritty/latte.toml"]
live_config_reload = false

[cursor]
unfocused_hollow = true

[debug]
highlight_damage = false
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.italic]
family = "Maple Mono"
style = "Italic"

[font.normal]
family = "Maple Mono"
style = "Regular"

# [mouse]
# enable = false

[window]
decorations = "none"
dynamic_padding = true
# opacity = 1.0
opacity = 0.90

[window.dimensions]
columns = 320
lines = 85
