draw_bold_text_with_bright_colors = false
[schemes]
[schemes.solarized_light]
[schemes.solarized_light.primary]
background = "#ffffff"
foreground = "#657b83"

[schemes.solarized_light.cursor]
text = "#fdf6e3"
cursor = "#657b83"

[schemes.solarized_light.normal]
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"

[schemes.solarized_light.bright]
black = "#002b36"
red = "#cb4b16"
green = "#586e75"
yellow = "#657b83"
blue = "#839496"
magenta = "#6c71c4"
cyan = "#93a1a1"
white = "#fdf6e3"

[schemes.solarized_dark]
[schemes.solarized_dark.primary]
background = "#ffffff"
foreground = "#839496"

[schemes.solarized_dark.cursor]
text = "#002b36"
cursor = "#839496"

[schemes.solarized_dark.normal]
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"

[schemes.solarized_dark.bright]
black = "#586e75"
red = "#cb4b16"
green = "#586e75"
yellow = "#657b83"
blue = "#839496"
magenta = "#6c71c4"
cyan = "#93a1a1"
white = "#fdf6e3"

[colors]
[colors.primary]
background = "#ffffff"
foreground = "#657b83"

[colors.cursor]
text = "#fdf6e3"
cursor = "#657b83"

[colors.normal]
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"

[colors.bright]
black = "#002b36"
red = "#cb4b16"
green = "#586e75"
yellow = "#657b83"
blue = "#839496"
magenta = "#6c71c4"
cyan = "#93a1a1"
white = "#fdf6e3"
